"""Read a repository's history and count how often it explains itself."""

from __future__ import annotations

import re
import subprocess
from pathlib import Path

from workspace_indexer.discovery import is_repo
from workspace_indexer.grounding.rationale_signals import RationaleSignals
from workspace_indexer.obs.logging import get_logger

log = get_logger("workspace_indexer.grounding.commits")

# ASCII unit and record separators. Commit messages are arbitrary text and
# routinely contain newlines, tabs, pipes and colons; these two bytes are the
# only delimiters a person will not type by accident.
_FIELD = "\x1e"
_RECORD = "\x1d"

# Recent history describes the code that exists. A ten-year-old repository's
# first thousand commits mostly explain files that were deleted years ago, and
# reading them makes the report slower and less true at the same time.
_MAX_COMMITS = 2000

_TIMEOUT = 60

# The form of an explanation. This detects that a reason was *offered*, never
# that it is correct or useful -- "because it was broken" matches. That is the
# honest limit of a lexical test, and the reason the report shows the share
# rather than claiming the history is good.
_RATIONALE = re.compile(
    r"\b("
    r"because|since it|so that|so we|so it|due to|owing to|in order to|"
    r"instead of|rather than|as opposed to|"
    r"root cause|caused by|the reason|which is why|the issue was|turned out|"
    r"to avoid|avoids?|prevents?|otherwise|"
    r"we (?:chose|decided|opted|need|must)|this (?:lets|allows|means)"
    r")\b",
    re.IGNORECASE,
)

# Subjects a merge tool wrote. Counted separately because a history of these
# scores well on every length-based measure while carrying no authored prose.
_AUTOGENERATED = re.compile(
    r"^(merged pr \d+|merge branch|merge pull request|merge remote|"
    r"squashed commit|automatic merge|revert \")",
    re.IGNORECASE,
)

_TICKET = re.compile(r"(#\d{1,6}\b|\b([A-Z]{2,10})-\d{1,6}\b)")

# Uppercase runs that look like a project key and are not one. Without this,
# "migrate to UTF-8" and "verify the SHA-1" read as work-item references and
# quietly inflate the one signal that redirects a user to another system.
_NOT_A_PROJECT_KEY = frozenset(
    {
        "UTF",
        "SHA",
        "ISO",
        "RFC",
        "MD",
        "SHA256",
        "AES",
        "RSA",
        "HTTP",
        "HTML",
        "CSS",
        "JSON",
        "XML",
        "SQL",
        "API",
        "URL",
        "URI",
        "UUID",
        "IPV",
        "TLS",
        "OAUTH",
        "JWT",
        "CVE",
        "PEP",
        "ES",
        "EC",
        "X",
    }
)


class CommitScanner:
    """One `git log` per repository, parsed in memory.

    Invokes `git` rather than a binding for the same reason discovery does: it
    is present on any machine that has the code checked out, and it already
    handles worktrees, shallow clones and detached HEADs correctly.
    """

    def __init__(self, max_commits: int = _MAX_COMMITS) -> None:
        self._max_commits = max_commits

    def scan(self, repo: Path) -> RationaleSignals | None:
        """Signals for `repo`, or None when there is no history to read.

        None and a zero-commit result are different answers and are kept
        different: a directory that is not a repository cannot be graded on its
        commit discipline, while an empty repository has been graded and found
        to have nothing.
        """
        raw = self._log(repo)
        if raw is None:
            # `git log` also fails on a repository that has no commits yet, so
            # the failure alone cannot tell the two apart -- and answering None
            # there would contradict the distinction this method promises.
            # Asked of git rather than read out of its stderr, which is
            # phrased differently across versions and locales.
            return RationaleSignals() if is_repo(repo) else None

        signals = RationaleSignals()
        for record in raw.split(_RECORD):
            if not record.strip():
                continue
            subject, _, body = record.partition(_FIELD)
            subject, body = subject.strip(), body.strip()
            signals.commits += 1
            if _AUTOGENERATED.match(subject):
                signals.autogenerated += 1
            message = f"{subject}\n{body}"
            if _RATIONALE.search(message):
                signals.with_rationale += 1
            if self._names_a_ticket(message):
                signals.with_ticket += 1

        log.debug(
            "grounding.commits_scanned",
            repo=repo.name,
            commits=signals.commits,
            rationale=signals.with_rationale,
        )
        return signals

    def _log(self, repo: Path) -> str | None:
        try:
            result = subprocess.run(
                [
                    "git",
                    "-C",
                    str(repo),
                    "log",
                    "--no-merges",
                    f"--max-count={self._max_commits}",
                    f"--pretty=format:%s{_FIELD}%b{_RECORD}",
                ],
                capture_output=True,
                text=True,
                timeout=_TIMEOUT,
                check=False,
            )
        except (OSError, subprocess.TimeoutExpired) as exc:
            log.debug("grounding.git_failed", repo=str(repo), error=str(exc))
            return None
        if result.returncode != 0:
            return None
        return result.stdout

    @staticmethod
    def _names_a_ticket(message: str) -> bool:
        for match in _TICKET.finditer(message):
            key = match.group(2)
            if key is None or key.upper() not in _NOT_A_PROJECT_KEY:
                return True
        return False
