"""What a repository's commit history says about why things are the way they are."""

from __future__ import annotations

from pydantic import BaseModel

# A ticket share this high means the team routinely records *where* the reason
# lives even when the message does not carry it. Below this it is incidental.
_TRACKER_HABIT = 0.25


class RationaleSignals(BaseModel):
    """Counts over non-merge commits. Deliberately raw.

    Every field is a count rather than a verdict so the thresholds live in one
    place (`GroundingSource`) and this stays a measurement. A scanner that
    graded its own output would make the grade untestable against real history.
    """

    commits: int = 0
    # Commits whose message states a reason, not just a change. The lexical
    # proxy is in `CommitScanner`, and it is a proxy: it detects the *form* of
    # an explanation, never its truth or usefulness.
    with_rationale: int = 0
    # Commits naming an issue or work item. Not an answer -- a pointer to one,
    # usually in a system this index cannot see.
    with_ticket: int = 0
    # Subjects written by a merge tool rather than a person ("Merged PR 412:").
    # Counted because a history can look rich by every length-based measure and
    # still be almost entirely machine-authored.
    autogenerated: int = 0

    @property
    def rationale_share(self) -> float:
        return self.with_rationale / self.commits if self.commits else 0.0

    @property
    def ticket_share(self) -> float:
        return self.with_ticket / self.commits if self.commits else 0.0

    @property
    def autogenerated_share(self) -> float:
        return self.autogenerated / self.commits if self.commits else 0.0

    @property
    def points_at_a_tracker(self) -> bool:
        """Do the commits habitually cite a ticket?

        Reported on its own rather than folded into a strength, because it
        inverts the meaning of a low rationale score: history that cites a work
        item for three commits in four has not lost the reason, it has stored
        it somewhere this index does not reach. The remedy is an integration,
        not better commit discipline, and those are different asks.
        """
        return self.ticket_share >= _TRACKER_HABIT
