"""What one repository can and cannot explain about itself."""

from __future__ import annotations

from pydantic import BaseModel

from workspace_indexer.grounding.grounding_source import GroundingSource
from workspace_indexer.grounding.rationale_signals import RationaleSignals
from workspace_indexer.grounding.source_strength import SourceStrength

# A history this machine-authored is not prose. Reported so a reader does not
# credit a repository for bodies that a merge tool generated.
_MOSTLY_AUTOGENERATED = 0.5

_ORDER = {
    SourceStrength.ABSENT: 0,
    SourceStrength.THIN: 1,
    SourceStrength.PRESENT: 2,
}


class UnitCoverage(BaseModel):
    """One repository's grounding, source by source.

    The verdict is the *best* source rather than an average, because these are
    alternatives and not components: a repository with thorough design
    documents and terse commits can answer "why", and averaging would mark it
    down for a redundancy it does not need.
    """

    label: str
    code_files: int
    sources: list[GroundingSource]
    # None when the unit is not a git repository at all -- a plain directory of
    # documents, say. Distinct from a repository whose history explains nothing.
    signals: RationaleSignals | None = None
    # False when the indexed files are no longer where the manifest says. Held
    # separately from "not a repository" because the two look identical to git
    # and mean opposite things: one is a fact about the code, the other is a
    # fact about the index, and only the second invalidates the whole row.
    on_disk: bool = True

    @property
    def verdict(self) -> SourceStrength:
        if not self.sources:
            return SourceStrength.ABSENT
        return max((s.strength for s in self.sources), key=lambda s: _ORDER[s])

    @property
    def notes(self) -> list[str]:
        """Findings that change what a reader should *do*, not just know."""
        out: list[str] = []
        if not self.on_disk:
            # Said first and alone: every other number here was computed from
            # sources that could not be read, so ranking them would be worse
            # than saying nothing.
            return [
                "the indexed files are no longer at their recorded paths, so nothing here "
                "was measured against real sources -- reindex before reading this row"
            ]

        signals = self.signals
        if signals is None:
            out.append("not a git repository, so no history was read")
            return out

        if signals.points_at_a_tracker and signals.rationale_share < 0.15:
            out.append(
                f"{signals.ticket_share:.0%} of commits cite a ticket but only "
                f"{signals.rationale_share:.0%} state a reason: the rationale for this "
                "repository most likely lives in the issue tracker, which this index "
                "does not read"
            )
        if signals.autogenerated_share >= _MOSTLY_AUTOGENERATED:
            out.append(
                f"{signals.autogenerated_share:.0%} of commit subjects were written by a "
                "merge tool, so history looks fuller than it reads"
            )
        if self.verdict is SourceStrength.ABSENT:
            out.append(
                "no source of intent was found; an agent asking why this code is the way "
                "it is cannot be answered from this repository, and generated prose would "
                "be invention rather than retrieval"
            )
        return out
