"""How one repository's sources combine into a verdict, and what gets said about it."""

from __future__ import annotations

from workspace_indexer.grounding import (
    GroundingSource,
    RationaleSignals,
    SourceStrength,
    UnitCoverage,
)


def source(strength: SourceStrength) -> GroundingSource:
    """A source pinned to a strength, so verdict logic is tested on its own."""
    found = {SourceStrength.ABSENT: 0, SourceStrength.THIN: 1, SourceStrength.PRESENT: 50}[strength]
    # 200 files, so a single document lands below one-per-hundred and is THIN.
    return GroundingSource.by_density("x", found, 200, detail="")


def test_the_verdict_is_the_best_source_not_the_average() -> None:
    """Sources are alternatives, not components.

    Thorough design docs answer "why" whether or not the commits also do, and
    averaging would mark a repository down for a redundancy it does not need.
    """
    coverage = UnitCoverage(
        label="repo",
        code_files=100,
        sources=[source(SourceStrength.PRESENT), source(SourceStrength.ABSENT)],
        signals=RationaleSignals(commits=10, with_rationale=5),
    )

    assert coverage.verdict is SourceStrength.PRESENT


def test_all_sources_absent_is_absent() -> None:
    coverage = UnitCoverage(
        label="repo",
        code_files=100,
        sources=[source(SourceStrength.ABSENT), source(SourceStrength.ABSENT)],
        signals=RationaleSignals(commits=10),
    )

    assert coverage.verdict is SourceStrength.ABSENT


def test_thin_beats_absent_but_does_not_reach_present() -> None:
    coverage = UnitCoverage(
        label="repo",
        code_files=100,
        sources=[source(SourceStrength.ABSENT), source(SourceStrength.THIN)],
        signals=RationaleSignals(commits=10),
    )

    assert coverage.verdict is SourceStrength.THIN


def test_no_sources_at_all_is_absent_not_a_crash() -> None:
    coverage = UnitCoverage(label="repo", code_files=0, sources=[], signals=None)

    assert coverage.verdict is SourceStrength.ABSENT


def test_a_history_that_cites_tickets_but_states_no_reasons_says_where_to_look() -> None:
    """The finding that changes what a reader should do.

    A low rationale score usually means "write better commits". With tickets on
    most commits it means the opposite: the reasons were recorded, somewhere
    this index does not reach, and the fix is an integration.
    """
    coverage = UnitCoverage(
        label="repo",
        code_files=100,
        sources=[source(SourceStrength.ABSENT)],
        signals=RationaleSignals(commits=170, with_rationale=11, with_ticket=121),
    )

    assert any("issue tracker" in note for note in coverage.notes)


def test_stated_reasons_suppress_the_tracker_note() -> None:
    """Tickets alongside real rationale are corroboration, not a redirection."""
    coverage = UnitCoverage(
        label="repo",
        code_files=100,
        sources=[source(SourceStrength.PRESENT)],
        signals=RationaleSignals(commits=311, with_rationale=96, with_ticket=227),
    )

    assert not any("issue tracker" in note for note in coverage.notes)


def test_a_mostly_machine_written_history_is_called_out() -> None:
    coverage = UnitCoverage(
        label="repo",
        code_files=100,
        sources=[source(SourceStrength.THIN)],
        signals=RationaleSignals(commits=170, with_rationale=11, autogenerated=157),
    )

    assert any("merge tool" in note for note in coverage.notes)


def test_absence_is_stated_plainly_including_what_not_to_do() -> None:
    """The report has to say generation would be invention.

    This is the whole point: an agent that cannot find a reason must be told
    none was recorded, because the alternative is prose that reads exactly like
    a retrieved one.
    """
    coverage = UnitCoverage(
        label="repo",
        code_files=100,
        sources=[source(SourceStrength.ABSENT)],
        signals=RationaleSignals(commits=10),
    )

    assert any("invention" in note for note in coverage.notes)


def test_a_non_repository_says_so_and_stops() -> None:
    """No history read is not the same as a history that explains nothing."""
    coverage = UnitCoverage(
        label="docs-only", code_files=0, sources=[source(SourceStrength.PRESENT)], signals=None
    )

    assert coverage.notes == ["not a git repository, so no history was read"]


def test_a_stale_row_says_so_and_says_nothing_else() -> None:
    """Found by running the report against an index whose files had moved.

    Every source reported "absent" -- which is what an unreadable path and an
    undocumented repository look like to git alike. Ranking the other findings
    underneath would dress a measurement of nothing as a finding about a
    codebase.
    """
    coverage = UnitCoverage(
        label="moved",
        code_files=100,
        sources=[source(SourceStrength.ABSENT)],
        signals=None,
        on_disk=False,
    )

    assert len(coverage.notes) == 1
    assert "reindex" in coverage.notes[0]
    assert not any("not a git repository" in note for note in coverage.notes)
