"""Reading rationale out of real git history.

Real repositories throughout: the scanner's job is to survive what people
actually type into commit messages, and a stubbed `git log` would only confirm
the format we already assumed.
"""

from __future__ import annotations

import subprocess
from pathlib import Path

import pytest

from tests.conftest import git_init
from workspace_indexer.grounding import CommitScanner

_IDENTITY = [
    "-c",
    "user.email=test@example.com",
    "-c",
    "user.name=Test",
    "-c",
    "commit.gpgsign=false",
]


def commit(repo: Path, subject: str, body: str = "") -> None:
    """One empty commit carrying the message under test."""
    message = [subject] if not body else [subject, body]
    args = ["git", *_IDENTITY, "commit", "-q", "--allow-empty"]
    for part in message:
        args += ["-m", part]
    subprocess.run(args, cwd=repo, check=True, capture_output=True)


@pytest.fixture
def repo(tmp_path: Path) -> Path:
    path = tmp_path / "repo"
    path.mkdir()
    (path / "seed.txt").write_text("seed", encoding="utf-8")
    git_init(path)
    return path


def test_a_directory_that_is_not_a_repository_returns_none(tmp_path: Path) -> None:
    """None means "could not be graded", which is not the same as scoring zero."""
    assert CommitScanner().scan(tmp_path) is None


def test_a_stated_reason_is_counted(repo: Path) -> None:
    commit(repo, "retry on 429", "The provider rate-limits bursts, so we back off.")

    signals = CommitScanner().scan(repo)

    assert signals is not None
    assert signals.with_rationale == 1


def test_a_bare_change_description_is_not(repo: Path) -> None:
    commit(repo, "update the retry count")
    commit(repo, "bump dependency versions")

    signals = CommitScanner().scan(repo)

    assert signals is not None
    assert signals.with_rationale == 0
    # Still counted as history -- the seed commit plus these two.
    assert signals.commits == 3


def test_rationale_in_the_body_counts_even_when_the_subject_is_terse(repo: Path) -> None:
    """Most real rationale lives below the subject line."""
    commit(repo, "fix login", "Sessions were dropped because the clock skewed.")

    signals = CommitScanner().scan(repo)

    assert signals is not None
    assert signals.with_rationale == 1


def test_merge_tool_subjects_are_flagged_as_autogenerated(repo: Path) -> None:
    """A history of these looks substantial by length and reads as nothing."""
    commit(repo, "Merged PR 412: add the export endpoint")
    commit(repo, "Merged PR 415: tidy the export endpoint")

    signals = CommitScanner().scan(repo)

    assert signals is not None
    assert signals.autogenerated == 2


def test_a_work_item_reference_is_recorded(repo: Path) -> None:
    commit(repo, "ERM-4821 add the export endpoint")
    commit(repo, "closes #317")

    signals = CommitScanner().scan(repo)

    assert signals is not None
    assert signals.with_ticket == 2


def test_technical_acronyms_are_not_mistaken_for_work_items(repo: Path) -> None:
    """`UTF-8` is not a ticket.

    Without the deny list these inflate the one signal that tells a user their
    rationale lives in another system -- sending them to a tracker that has
    nothing in it.
    """
    commit(repo, "migrate the reader to UTF-8")
    commit(repo, "verify the SHA-1 before trusting the cache")

    signals = CommitScanner().scan(repo)

    assert signals is not None
    assert signals.with_ticket == 0


def test_a_message_is_counted_once_however_many_reasons_it_gives(repo: Path) -> None:
    commit(
        repo,
        "drop the cache",
        "It was stale because the key ignored the branch, so we removed it "
        "rather than adding a second key.",
    )

    signals = CommitScanner().scan(repo)

    assert signals is not None
    assert signals.with_rationale == 1


def test_multiline_messages_do_not_split_into_extra_commits(repo: Path) -> None:
    """The delimiter has to survive newlines, which every real body contains."""
    commit(repo, "restructure", "first line\n\nsecond line\n\nthird line")

    signals = CommitScanner().scan(repo)

    assert signals is not None
    assert signals.commits == 2  # the seed commit and this one


def test_the_scan_is_capped_at_the_requested_depth(repo: Path) -> None:
    """Old history describes deleted code and costs time to read."""
    for n in range(6):
        commit(repo, f"change {n}")

    signals = CommitScanner(max_commits=3).scan(repo)

    assert signals is not None
    assert signals.commits == 3


def test_shares_are_zero_rather_than_undefined_on_an_empty_history(tmp_path: Path) -> None:
    path = tmp_path / "empty"
    path.mkdir()
    git_init(path, commit=False)

    signals = CommitScanner().scan(path)

    assert signals is not None
    assert signals.commits == 0
    assert signals.rationale_share == 0.0
    assert signals.ticket_share == 0.0
    assert signals.autogenerated_share == 0.0
    assert signals.points_at_a_tracker is False
